-- =====================================================
-- File: 04_views_optional.sql
-- Purpose: Create reusable SQL Views for analytics
-- Database: online_sales
-- =====================================================

-- Use the project database
USE online_sales;

-- -----------------------------------------------------
-- Drop views if they already exist (safe re-run)
-- -----------------------------------------------------
DROP VIEW IF EXISTS customer_order_summary;
DROP VIEW IF EXISTS product_sales_summary;
DROP VIEW IF EXISTS monthly_revenue;
DROP VIEW IF EXISTS category_revenue_summary;

-- -----------------------------------------------------
-- View 1: Customer Order Summary
-- Shows total orders and total amount spent per customer
-- -----------------------------------------------------
CREATE VIEW customer_order_summary AS
SELECT 
    c.customer_id,
    c.name AS customer_name,
    COUNT(o.order_id) AS total_orders,
    SUM(p.amount) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN payments p ON o.order_id = p.order_id
GROUP BY c.customer_id, c.name;

-- -----------------------------------------------------
-- View 2: Product Sales Summary
-- Shows how many units of each product are sold
-- -----------------------------------------------------
CREATE VIEW product_sales_summary AS
SELECT
    pr.product_id,
    pr.product_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM products pr
JOIN order_items oi ON pr.product_id = oi.product_id
GROUP BY pr.product_id, pr.product_name;

-- -----------------------------------------------------
-- View 3: Monthly Revenue
-- Shows total revenue generated per month
-- -----------------------------------------------------
CREATE VIEW monthly_revenue AS
SELECT
    MONTH(o.order_date) AS month,
    SUM(p.amount) AS total_revenue
FROM orders o
JOIN payments p ON o.order_id = p.order_id
GROUP BY MONTH(o.order_date);

-- -----------------------------------------------------
-- View 4: Category-wise Revenue Summary
-- Shows revenue generated by each product category
-- -----------------------------------------------------
CREATE VIEW category_revenue_summary AS
SELECT
    cat.category_name,
    SUM(p.amount) AS total_revenue
FROM categories cat
JOIN products pr ON cat.category_id = pr.category_id
JOIN order_items oi ON pr.product_id = oi.product_id
JOIN payments p ON oi.order_id = p.order_id
GROUP BY cat.category_name;

-- -----------------------------------------------------
-- END OF FILE
-- -----------------------------------------------------
